#include "consolefunc.h"

#include "windows.h"

const short SCENE_DESCRIPTION = FOREGROUND_RED | FOREGROUND_GREEN;
const short HEADING = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const short ITEMS_HEADING = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const short ITEMS = FOREGROUND_GREEN;
const short DISCIPLINES_HEADING = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const short DISCIPLINES = FOREGROUND_GREEN;
const short HEALTH_OK = FOREGROUND_GREEN;
const short HEALTH_GOOD = FOREGROUND_GREEN | FOREGROUND_RED;
const short HEALTH_BAD = FOREGROUND_RED;
const short COMMAND_LINE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
const short ACTIONS = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const short DEAD = FOREGROUND_RED | FOREGROUND_INTENSITY;
const short CHARACTER_NAME = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;


void SetFontColor(short color)
{
	WORD consoleAttr = color;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), consoleAttr);
}