#ifndef __GAME_COMPONENT_DEFINITIONS_H__
#define __GAME_COMPONENT_DEFINITIONS_H__


#define GAME_COMP_COUNT 6

enum GameComponentType {
	GAME_COMP_TRANSFORM					= 0,
	GAME_COMP_RENDER_RIGID_BODY			= 1,
	GAME_COMP_RENDER_TERRAIN_DECAL		= 2,
	GAME_COMP_LOGIC 					= 3,
	GAME_COMP_INPUT 					= 4,
	GAME_COMP_PHYSICS					= 5,
};



enum GameTaskMessageType {
	GAME_TASK_UNKNOWN				= 0,
	GAME_TASK_TRANSFORM_UPDATE		= 1
};





#endif // __GAME_COMPONENT_DEFINITIONS_H__