#ifndef __GAME_COMPONENT_DEFINITIONS_H__
#define __GAME_COMPONENT_DEFINITIONS_H__


#define GAME_COMP_COUNT 8

enum GameComponentType {
	GAME_COMP_TRANSFORM					= 0,
	GAME_COMP_RENDER_RIGID_BODY			= 1,
	GAME_COMP_RENDER_TERRAIN_DECAL		= 2,
	GAME_COMP_RENDER_CAMERA				= 3,
	GAME_COMP_RENDER_MOVEABLE			= 4,
	GAME_COMP_PHYSICS_RIGID_BODY		= 5,
	GAME_COMP_PHYSICS_STATIC_OBJECT		= 6,
	GAME_COMP_LOGIC_FREE_CAMERA			= 7,
	//GAME_COMP_LOGIC_FREE_CAMERA		= 8,
	GAME_COMP_INPUT_FREE_CAMERA			= 9,
	GAME_COMP_INPUT_CHARACTER			= 10,
	
};



enum GameTaskMessageType {
	GAME_TASK_UNKNOWN				= 0,
	GAME_TASK_TRANSFORM_UPDATE		= 1
};





#endif // __GAME_COMPONENT_DEFINITIONS_H__