#ifndef __GAME_COMPONENT_DEFINITIONS_H__
#define __GAME_COMPONENT_DEFINITIONS_H__


#define GAME_COMP_COUNT 5

enum GameComponentType {
	GAME_COMP_TRANSFORM					= 0,
	GAME_COMP_RENDER_RIGID_BODY			= 1,
	GAME_COMP_LOGIC 					= 2,
	GAME_COMP_INPUT 					= 3,
	GAME_COMP_PHYSICS					= 4,
};



enum GameComponentMaskType {
	GAME_COMP_MASK_TRANSFORM			= 1<<GAME_COMP_TRANSFORM,
	GAME_COMP_MASK_RENDER_RIGID_BODY	= 1<<GAME_COMP_RENDER_RIGID_BODY,
	GAME_COMP_MASK_LOGIC 				= 1<<GAME_COMP_LOGIC,
	GAME_COMP_MASK_INPUT 				= 1<<GAME_COMP_INPUT,
	GAME_COMP_MASK_PHYSICS				= 1<<GAME_COMP_PHYSICS,
	GAME_COMP_MASK_ALL					= wxUINT32_MAX,
};


enum GameTaskMessageType {
	GAME_TASK_UNKNOWN				= 0,
	GAME_TASK_TRANSFORM_UPDATE		= 1
};





#endif // __GAME_COMPONENT_DEFINITIONS_H__