#ifndef __LONE_WOLF_CHARACTER_H__
#define __LONE_WOLF_CHARACTER_H__


enum Disciplines {
	DISCIPLINE_UNKNOWN		= 0,
	DISCIPLINE_CAMOUFLAGE	= 1,
	DISCIPLINE_HUNTING		= 2,
	DISCIPLINE_SIXTH_SENSE	= 3,
	DISCIPLINE_TRACKING		= 4,
	DISCIPLINE_HEALING		= 5,
	DISCIPLINE_WEAPONSKILL	= 6,
	DISCIPLINE_MINDSHIELD	= 7,
	DISCIPLINE_MINDBLAST	= 8,
	DISCIPLINE_ANIMAL_KINDSHIP	= 9,
	DISCIPLINE_MIND_OVER_MATTER = 10
};

class Character {

public:
	Character() {}
};



#endif //__LONE_WOLF_CHARACTER_H__