#ifndef __GAME_TESTING_DEFINITIONS_H__
#define __GAME_TESTING_DEFINITIONS_H__

enum GameEntitiesDef {
	ENTITY_DEF_UNKNOWN  	= 0,
	ENTITY_DEF_TESTBOX1 	= 1,
	ENTITY_DEF_TESTGROUND	= 2,
	ENTITY_DEF_TESTORB		= 3
};

enum GameAnimationDef {
	ANIM_DEF_UNKNOWN 	= 0,
	ANIM_DEF_TESTORB	= 1
};

#endif //__GAME_TESTING_DEFINITIONS_H__