#ifndef __GAME_KEY_CODES_AND_TEXTS_DEFINITIONS_H__
#define __GAME_KEY_CODES_AND_TEXTS_DEFINITIONS_H__

#include <wx/chartype.h>
#include <OIS/OISKeyboard.h>

struct KeyTableRow {
	OIS::KeyCode 	m_keyCode;
	const wxChar*  	m_keyName;
};


static const KeyTableRow KeyTable[] = 
{
	{ OIS::KC_UNASSIGNED	, wxT("")	 				},
	{ OIS::KC_ESCAPE		, wxT("key_escape")   		},   
	{ OIS::KC_1 			, wxT("key_1")   			},       
	{ OIS::KC_2             , wxT("key_2")				},
	{ OIS::KC_3             , wxT("key_3")				},
	{ OIS::KC_4             , wxT("key_4")				},
	{ OIS::KC_5             , wxT("key_5")				},
	{ OIS::KC_6             , wxT("key_6")				},
	{ OIS::KC_7             , wxT("key_7")				},
	{ OIS::KC_8             , wxT("key_8")				},
	{ OIS::KC_9             , wxT("key_9")				},
	{ OIS::KC_0             , wxT("key_0")				},
	{ OIS::KC_MINUS         , wxT("key_minus")			},
	{ OIS::KC_EQUALS        , wxT("key_equals")			},
	{ OIS::KC_BACK          , wxT("key_back")			},
	{ OIS::KC_TAB           , wxT("key_tab")			},
	{ OIS::KC_Q             , wxT("key_q")				},
	{ OIS::KC_W             , wxT("key_w")				},
	{ OIS::KC_E             , wxT("key_e")				},
	{ OIS::KC_R             , wxT("key_r")				},
	{ OIS::KC_T             , wxT("key_t")				},
	{ OIS::KC_Y             , wxT("key_y")				},
	{ OIS::KC_U             , wxT("key_u")				},
	{ OIS::KC_I             , wxT("key_i")				},
	{ OIS::KC_O             , wxT("key_o")				},
	{ OIS::KC_P             , wxT("key_p")				},
	{ OIS::KC_LBRACKET      , wxT("key_lbracket")		},
	{ OIS::KC_RBRACKET      , wxT("key_rbracket")		},
	{ OIS::KC_RETURN        , wxT("key_return")			},
	{ OIS::KC_LCONTROL      , wxT("key_lcontrol")		},
	{ OIS::KC_A             , wxT("key_a")				},
	{ OIS::KC_S             , wxT("key_s")				},
	{ OIS::KC_D             , wxT("key_d")				},
	{ OIS::KC_F             , wxT("key_f")				},
	{ OIS::KC_G             , wxT("key_g")				},
	{ OIS::KC_H             , wxT("key_h")				},
	{ OIS::KC_J             , wxT("key_j")				},
	{ OIS::KC_K             , wxT("key_k")				},
	{ OIS::KC_L             , wxT("key_l")				},
	{ OIS::KC_SEMICOLON     , wxT("key_semicolon")		},
	{ OIS::KC_APOSTROPHE    , wxT("key_apostrophe")		},
	{ OIS::KC_GRAVE         , wxT("key_grave")			},
	{ OIS::KC_LSHIFT        , wxT("key_lshift")			},
	{ OIS::KC_BACKSLASH     , wxT("key_backslash")		},
	{ OIS::KC_Z             , wxT("key_z")				},
	{ OIS::KC_X             , wxT("key_x")				},
	{ OIS::KC_C             , wxT("key_c")				},
	{ OIS::KC_V             , wxT("key_v")				},
	{ OIS::KC_B             , wxT("key_b")				},
	{ OIS::KC_N             , wxT("key_n")				},
	{ OIS::KC_M             , wxT("key_m")				},
	{ OIS::KC_COMMA         , wxT("key_comma")			},
	{ OIS::KC_PERIOD        , wxT("key_period")			},
	{ OIS::KC_SLASH         , wxT("key_slash")			},
	{ OIS::KC_RSHIFT        , wxT("key_rshift")			},
	{ OIS::KC_MULTIPLY      , wxT("key_multiply")		},
	{ OIS::KC_LMENU         , wxT("key_lmenu")			},
	{ OIS::KC_SPACE         , wxT("key_space")			},
	{ OIS::KC_CAPITAL       , wxT("key_capital")		},
	{ OIS::KC_F1            , wxT("key_f1")				},
	{ OIS::KC_F2            , wxT("key_f2")				},
	{ OIS::KC_F3            , wxT("key_f3")				},
	{ OIS::KC_F4            , wxT("key_f4")				},
	{ OIS::KC_F5            , wxT("key_f5")				},
	{ OIS::KC_F6            , wxT("key_f6")				},
	{ OIS::KC_F7            , wxT("key_f7")				},
	{ OIS::KC_F8            , wxT("key_f8")				},
	{ OIS::KC_F9            , wxT("key_f9")				},
	{ OIS::KC_F10           , wxT("key_f10")			},
	{ OIS::KC_NUMLOCK       , wxT("key_numlock")		},
	{ OIS::KC_SCROLL        , wxT("key_scroll")			},
	{ OIS::KC_NUMPAD7       , wxT("key_numpad7")		},
	{ OIS::KC_NUMPAD8       , wxT("key_numpad8")		},
	{ OIS::KC_NUMPAD9       , wxT("key_numpad9")		},
	{ OIS::KC_SUBTRACT      , wxT("key_subtract")		},
	{ OIS::KC_NUMPAD4       , wxT("key_numpad4")		},
	{ OIS::KC_NUMPAD5       , wxT("key_numpad5")		},
	{ OIS::KC_NUMPAD6       , wxT("key_numpad6")		},
	{ OIS::KC_ADD           , wxT("key_add")			},
	{ OIS::KC_NUMPAD1       , wxT("key_numpad1")		},
	{ OIS::KC_NUMPAD2       , wxT("key_numpad2")		},
	{ OIS::KC_NUMPAD3       , wxT("key_numpad3")		},
	{ OIS::KC_NUMPAD0       , wxT("key_numpad0")		},
	{ OIS::KC_DECIMAL       , wxT("key_decimal")		},
	{ OIS::KC_OEM_102       , wxT("key_oem_102")		},
	{ OIS::KC_F11           , wxT("key_f11")			},
	{ OIS::KC_F12           , wxT("key_f12")			},
	{ OIS::KC_F13           , wxT("key_f13")			},
	{ OIS::KC_F14           , wxT("key_f14")			},
	{ OIS::KC_F15           , wxT("key_f15")			},
	{ OIS::KC_KANA          , wxT("key_kana")			},
	{ OIS::KC_ABNT_C1       , wxT("key_abnt_c1")		},
	{ OIS::KC_CONVERT       , wxT("key_convert")		},
	{ OIS::KC_NOCONVERT     , wxT("key_noconvert")		},
	{ OIS::KC_YEN           , wxT("key_yen")			},
	{ OIS::KC_ABNT_C2       , wxT("key_abnt_c2")		},
	{ OIS::KC_NUMPADEQUALS  , wxT("key_numpadequals")	},
	{ OIS::KC_PREVTRACK     , wxT("key_prevtrack")		},
	{ OIS::KC_AT            , wxT("key_at")				},
	{ OIS::KC_COLON         , wxT("key_colon")			},
	{ OIS::KC_UNDERLINE     , wxT("key_underline")		},
	{ OIS::KC_KANJI         , wxT("key_kanji")			},
	{ OIS::KC_STOP          , wxT("key_stop")			},
	{ OIS::KC_AX            , wxT("key_ax")				},
	{ OIS::KC_UNLABELED     , wxT("key_unlabeled")		},
	{ OIS::KC_NEXTTRACK     , wxT("key_nexttrack")		},
	{ OIS::KC_NUMPADENTER   , wxT("key_numpadenter")	},
	{ OIS::KC_RCONTROL      , wxT("key_rcontrol")		},
	{ OIS::KC_MUTE          , wxT("key_mute")			},
	{ OIS::KC_CALCULATOR    , wxT("key_calculator")		},
	{ OIS::KC_PLAYPAUSE     , wxT("key_playpause")		},
	{ OIS::KC_MEDIASTOP     , wxT("key_mediastop")		},
	{ OIS::KC_VOLUMEDOWN    , wxT("key_volumedown")		},
	{ OIS::KC_VOLUMEUP      , wxT("key_volumeup")		},
	{ OIS::KC_WEBHOME       , wxT("key_webhome")		},
	{ OIS::KC_NUMPADCOMMA   , wxT("key_numpadcomma")	},
	{ OIS::KC_DIVIDE        , wxT("key_divide")			},
	{ OIS::KC_SYSRQ         , wxT("key_sysrq")			},
	{ OIS::KC_RMENU         , wxT("key_rmenu")			},
	{ OIS::KC_PAUSE         , wxT("key_pause")			},
	{ OIS::KC_HOME          , wxT("key_home")			},
	{ OIS::KC_UP            , wxT("key_up")				},
	{ OIS::KC_PGUP          , wxT("key_pgup")			},
	{ OIS::KC_LEFT          , wxT("key_left")			},
	{ OIS::KC_RIGHT         , wxT("key_right")			},
	{ OIS::KC_END           , wxT("key_end")			},
	{ OIS::KC_DOWN          , wxT("key_down")			},
	{ OIS::KC_PGDOWN        , wxT("key_pgdown")			},
	{ OIS::KC_INSERT        , wxT("key_insert")			},
	{ OIS::KC_DELETE        , wxT("key_delete")			},
	{ OIS::KC_LWIN          , wxT("key_lwin")			},
	{ OIS::KC_RWIN          , wxT("key_rwin")			},
	{ OIS::KC_APPS          , wxT("key_apps")			},
	{ OIS::KC_POWER         , wxT("key_power")			},
	{ OIS::KC_SLEEP         , wxT("key_sleep")			},
	{ OIS::KC_WAKE          , wxT("key_wake")			},
	{ OIS::KC_WEBSEARCH     , wxT("key_websearch")		},
	{ OIS::KC_WEBFAVORITES  , wxT("key_webfavorites")	},
	{ OIS::KC_WEBREFRESH    , wxT("key_webrefresh")		},
	{ OIS::KC_WEBSTOP       , wxT("key_webstop")		},
	{ OIS::KC_WEBFORWARD    , wxT("key_webforward")		},
	{ OIS::KC_WEBBACK       , wxT("key_webback")		},
	{ OIS::KC_MYCOMPUTER    , wxT("key_mycomputer")		},
	{ OIS::KC_MAIL          , wxT("key_mail")			},
	{ OIS::KC_MEDIASELECT   , wxT("key_mediaselect")	},

};



#endif //__GAME_KEY_CODES_AND_TEXTS_DEFINITIONS_H__